---
- name: ensure pumacorn init.d config is created
  template: src=initd_pumacorn.j2 dest=/etc/init.d/{{ rails_deploy_app_name }} mode=0755

- name: ensure pumacorn starts on a fresh reboot
  service: name={{ rails_deploy_app_name }} enabled=yes

